require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FunniesController do

  # This should return the minimal set of attributes required to create a valid
  # Funny. As you add validations to Funny, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "content" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FunniesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all funnies as @funnies" do
      funny = Funny.create! valid_attributes
      get :index, {}, valid_session
      assigns(:funnies).should eq([funny])
    end
  end

  describe "GET show" do
    it "assigns the requested funny as @funny" do
      funny = Funny.create! valid_attributes
      get :show, {:id => funny.to_param}, valid_session
      assigns(:funny).should eq(funny)
    end
  end

  describe "GET new" do
    it "assigns a new funny as @funny" do
      get :new, {}, valid_session
      assigns(:funny).should be_a_new(Funny)
    end
  end

  describe "GET edit" do
    it "assigns the requested funny as @funny" do
      funny = Funny.create! valid_attributes
      get :edit, {:id => funny.to_param}, valid_session
      assigns(:funny).should eq(funny)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Funny" do
        expect {
          post :create, {:funny => valid_attributes}, valid_session
        }.to change(Funny, :count).by(1)
      end

      it "assigns a newly created funny as @funny" do
        post :create, {:funny => valid_attributes}, valid_session
        assigns(:funny).should be_a(Funny)
        assigns(:funny).should be_persisted
      end

      it "redirects to the created funny" do
        post :create, {:funny => valid_attributes}, valid_session
        response.should redirect_to(Funny.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved funny as @funny" do
        # Trigger the behavior that occurs when invalid params are submitted
        Funny.any_instance.stub(:save).and_return(false)
        post :create, {:funny => { "content" => "invalid value" }}, valid_session
        assigns(:funny).should be_a_new(Funny)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Funny.any_instance.stub(:save).and_return(false)
        post :create, {:funny => { "content" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested funny" do
        funny = Funny.create! valid_attributes
        # Assuming there are no other funnies in the database, this
        # specifies that the Funny created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Funny.any_instance.should_receive(:update).with({ "content" => "MyString" })
        put :update, {:id => funny.to_param, :funny => { "content" => "MyString" }}, valid_session
      end

      it "assigns the requested funny as @funny" do
        funny = Funny.create! valid_attributes
        put :update, {:id => funny.to_param, :funny => valid_attributes}, valid_session
        assigns(:funny).should eq(funny)
      end

      it "redirects to the funny" do
        funny = Funny.create! valid_attributes
        put :update, {:id => funny.to_param, :funny => valid_attributes}, valid_session
        response.should redirect_to(funny)
      end
    end

    describe "with invalid params" do
      it "assigns the funny as @funny" do
        funny = Funny.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Funny.any_instance.stub(:save).and_return(false)
        put :update, {:id => funny.to_param, :funny => { "content" => "invalid value" }}, valid_session
        assigns(:funny).should eq(funny)
      end

      it "re-renders the 'edit' template" do
        funny = Funny.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Funny.any_instance.stub(:save).and_return(false)
        put :update, {:id => funny.to_param, :funny => { "content" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested funny" do
      funny = Funny.create! valid_attributes
      expect {
        delete :destroy, {:id => funny.to_param}, valid_session
      }.to change(Funny, :count).by(-1)
    end

    it "redirects to the funnies list" do
      funny = Funny.create! valid_attributes
      delete :destroy, {:id => funny.to_param}, valid_session
      response.should redirect_to(funnies_url)
    end
  end

end
